#!/bin/bash
CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CRICCOMINI_GITHUB_IO="$CWD/../criccomini.github.io"

if [ ! -d "$CRICCOMINI_GITHUB_IO" ]; then
  echo "Error: unable to find directory $CRICCOMINI_GITHUB_IO"
  exit 1
fi

echo "Pushing from $CRICCOMINI_GITHUB_IO"

echo "== Building site with Jekyll =="
jekyll build
echo "== Copying site to $CRICCOMINI_GITHUB_IO"
cp -r $CWD/_site/* $CRICCOMINI_GITHUB_IO
cd $CRICCOMINI_GITHUB_IO
echo "== Committing changes =="
git add .
git commit -am"release $(date)"
echo "== Pushing changes =="
git push
echo "== Push successufl =="
cd $CWD
